name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal
      - name: Create Release
        id: create_release
        run: |
          RELEASE_TAG="v$(date +'%Y%m%d%H%M%S')"
          mkdir -p release
          cp ./bin/Debug/net8.0/YourApp.exe release/YourApp.exe
          zip -r release/YourApp.zip release/
          gh release create $RELEASE_TAG release/YourApp.zip --title "Release $RELEASE_TAG" --notes "Automated release created via GitHub Actions"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
