name: .NET

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal

      # Publish for Windows (creating an .exe)
      - name: Publish for Windows
        run: dotnet publish -c Release -r win-x64 --self-contained true -o ./output/windows

      # Zip Windows build output
      - name: Zip Windows build
        run: zip -r windows_build.zip ./output/windows/*

      # Upload the Windows build artifact
      - name: Upload Windows build artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-build-${{ github.run_number }}
          path: windows_build.zip
